"""EvidenceBound public API."""
from .api import EvidenceBound
from .canonical import CANONICALIZATION_VERSION, CanonicalizationError, canonical_bytes, digest
from .events import Event, EventSink, ListEventSink, NullEventSink
from .graph import DependencyGraph, GraphError
from .models import (
    ActionDecision,
    ApplicabilityStatus,
    Checkpoint,
    EvidenceAssessment,
    EvidenceRecord,
    EvidenceState,
    IntegrityStatus,
    InvalidationReason,
    PolicyBinding,
    ProofReceipt,
    ProvenanceRecord,
    VerificationResult,
)
from .persistence import (
    PERSISTED_RECORD_VERSION,
    PERSISTENCE_SCHEMA_VERSION,
    PersistenceError,
    PersistenceIntegrityError,
    PersistenceStore,
    UnsupportedPersistenceSchema,
)
from .recovery import RecoveryPlan, action_after_recovery, plan_recovery
from .replay import ReplayConflict, ReplayGuard, ReplayStatus
from .signing import (
    KeyState,
    ReceiptSigner,
    ReceiptVerifier,
    SignatureCheck,
    SignatureCheckStatus,
    SignedProofReceipt,
    SignedReceiptStatus,
    SignedReceiptVerification,
    sign_receipt,
    signed_receipt_bytes,
    verify_signed_receipt,
)
from .verification import (
    checkpoint_digest,
    evidence_digest,
    verify_checkpoint,
    verify_receipt,
    verify_verification_receipt,
)

__version__ = "0.3.0"

__all__ = [
    "ActionDecision",
    "ApplicabilityStatus",
    "CANONICALIZATION_VERSION",
    "CanonicalizationError",
    "Checkpoint",
    "DependencyGraph",
    "EvidenceAssessment",
    "EvidenceBound",
    "EvidenceRecord",
    "EvidenceState",
    "Event",
    "EventSink",
    "GraphError",
    "IntegrityStatus",
    "InvalidationReason",
    "KeyState",
    "ListEventSink",
    "NullEventSink",
    "PERSISTED_RECORD_VERSION",
    "PERSISTENCE_SCHEMA_VERSION",
    "PersistenceError",
    "PersistenceIntegrityError",
    "PersistenceStore",
    "PolicyBinding",
    "ProofReceipt",
    "ProvenanceRecord",
    "ReceiptSigner",
    "ReceiptVerifier",
    "RecoveryPlan",
    "ReplayConflict",
    "ReplayGuard",
    "ReplayStatus",
    "SignatureCheck",
    "SignatureCheckStatus",
    "SignedProofReceipt",
    "SignedReceiptStatus",
    "SignedReceiptVerification",
    "UnsupportedPersistenceSchema",
    "VerificationResult",
    "action_after_recovery",
    "canonical_bytes",
    "checkpoint_digest",
    "digest",
    "evidence_digest",
    "plan_recovery",
    "sign_receipt",
    "signed_receipt_bytes",
    "verify_checkpoint",
    "verify_receipt",
    "verify_signed_receipt",
    "verify_verification_receipt",
]
